// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    ContactItem: typeof import('./../src/views/contacts/components/ContactItem.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    IconCross: typeof import('./../src/components/icons/IconCross.vue')['default']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    JobOpeningsList: typeof import('./../src/views/jobOpenings/components/JobOpeningsList.vue')['default']
    JobOpeningsMultiselect: typeof import('./../src/views/jobOpenings/components/JobOpeningsMultiselect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
