// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/Button.vue')['default']
    CardList: typeof import('./../src/components/CardList.vue')['default']
    Categories: typeof import('./../src/components/Categories.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    Container: typeof import('./../src/components/Container.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    Features: typeof import('./../src/components/Features.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    Hero: typeof import('./../src/components/Hero.vue')['default']
    Portal: typeof import('./../src/plugins/portal/Portal.vue')['default']
    PortalTarget: typeof import('./../src/plugins/portal/PortalTarget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
